baseURL: "https://gabesekeres.com/" 
title: Gabe Sekeres
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
          params:
            description: "View current research projects."
        - name: Papers
          url: papers/
          weight: 2
          params:
            description: "View publications and preprints."
        - name: Teaching
          url: teaching/
          weight: 3
          params:
            description: "View teaching materials."
        - name: Resources
          url: resources/
          weight: 4
          params:
            description: "View resources."
        - name: Location
          url: location/
          weight: 5
          params:
            description: "View location and contact information."

params:
    description: "Gabe Sekeres's academic website."
    author: Gabe Sekeres
    # googleAnalyticsID: "G-XXXXX"
    customCSS: ["/assets/css/common/custom.css", "/assets/css/noise-tool.css"]
    customJS: ["/assets/js/noise-tool.js"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","research","teaching","location","resources"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Gabe Sekeres
          subtitle: "I am a second-year PhD student in the Department of Economics at Cornell University. My research focuses on the intersection of microeconomic theory and computer science, with particular interest in mechanism design, algorithmic game theory, and learning in economic environments.<br><br>Prior to Cornell, I was a predoctoral research fellow at Stanford University, working with [Laurence Baker](https://healthpolicy.fsi.stanford.edu/people/laurence_c_baker) and [Eric Sun](https://profiles.stanford.edu/eric-sun). I hold a B.A. in Economics and Mathematics from Haverford College.<br><br>My full CV is available [here](/cv/gabe_sekeres_cv.pdf)."

          imageUrl: "headshot.jpg"
          imageLazy: true
          buttons:
            - name: Research
              url: research/
            - name: Papers
              url: papers/
            - name: Teaching
              url: teaching/
            - name: Resources
              url: resources/
            - name: Location
              url: location/
    socialIcons:
        - name: CV
          url: /cv/gabe_sekeres_cv.pdf
        - name: Email
          url: mailto:gs754@cornell.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=l0QBiTIAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/gsekeres
        - name: LinkedIn
          url: https://www.linkedin.com/in/gabriel-sekeres-0526aa174/
        - name: Twitter
          url: https://twitter.com/GabeSekeres

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gabe Sekeres"
      icon: favicon/favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2